// <auto-generated />
using System;
using LagerverwaltungModern25._04._2025.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LagerverwaltungModern25._04._2025.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250509070339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bestand")
                        .HasColumnType("int");

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KategorieId");

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolleId");

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Bestellung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Bestelldatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("BenutzerId");

                    b.ToTable("Bestellungen");
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Kategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OberkategorieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OberkategorieId");

                    b.ToTable("Kategorien");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Werkzeuge"
                        });
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Rolle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rollen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mitarbeiter"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lagerleiter"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Buchhaltung"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gast"
                        });
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Warenausgang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.ToTable("Warenausgänge");
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Artikel", b =>
                {
                    b.HasOne("LagerverwaltungModern25._04._2025.Models.Kategorie", "Kategorie")
                        .WithMany("Artikel")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Benutzer", b =>
                {
                    b.HasOne("LagerverwaltungModern25._04._2025.Models.Rolle", "Rolle")
                        .WithMany("Benutzer")
                        .HasForeignKey("RolleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rolle");
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Bestellung", b =>
                {
                    b.HasOne("LagerverwaltungModern25._04._2025.Models.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagerverwaltungModern25._04._2025.Models.Benutzer", "Benutzer")
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Kategorie", b =>
                {
                    b.HasOne("LagerverwaltungModern25._04._2025.Models.Kategorie", "Oberkategorie")
                        .WithMany("Unterkategorien")
                        .HasForeignKey("OberkategorieId");

                    b.Navigation("Oberkategorie");
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Warenausgang", b =>
                {
                    b.HasOne("LagerverwaltungModern25._04._2025.Models.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Kategorie", b =>
                {
                    b.Navigation("Artikel");

                    b.Navigation("Unterkategorien");
                });

            modelBuilder.Entity("LagerverwaltungModern25._04._2025.Models.Rolle", b =>
                {
                    b.Navigation("Benutzer");
                });
#pragma warning restore 612, 618
        }
    }
}
